[a.a]
b = 1

[[arr]]

[arr.T.a]
b = 1

[arr.t.a]
b = 1

[[arr]]

[arr.T.a]
b = 2

[arr.t.a]
b = 2

[b.a]
b = 1

[c.a]
b = 1

[d.a]
b = 1

[e.a]
b = 1

[inline.a]
b = 42

[many.dots.here.dot.dot.dot.a.b]
c = 1
d = 2

[tbl.a.b.c.d]
e = 1

[tbl.x.a.b.c.d]
e = 1
