backslash = "This string has a \\\\ backslash character."
backspace = "This string has a \\b backspace character."
carriage = "This string has a \\r carriage return character."
formfeed = "This string has a \\f form feed character."
newline = "This string has a \\n new line character."
slash = "This string has a \\/ slash character."
tab = "This string has a \\t tab character."
